### ISSUE TITLE
CMAKE Build issues

### ISSUE THREAD

**Issue by Nathan127** [nvpro-samples/vk_raytracing_tutorial#1]
I'm having a few issues building the project to start the tutorial. I have downloaded and set up the 3 repo's and structured them as per the tutorial, the errors occur when hitting 'Configure' on Cmake.

The first error is: "MISSING: unable to find VULKAN_LIB files (Lib/vulkan-1.lib, Lib/vulkan-1.lib)" As far as I can tell, vulkan-1.lib hasn't been included in the Vulkan SDK for quite some time.

The second error I get is: 
"CMake Error at C:/RT Tutorial/shared_sources/CMakeLists_include.txt:1012 (add_subdirectory):
  The binary directory

    C:/RT Tutorial/Build/shared_sources

  is already used to build a source directory.  It cannot be used to build
  source directory

    C:/RT Tutorial/shared_sources

  Specify a unique binary directory name.
Call Stack (most recent call first):
  ray_tracing__before/CMakeLists.txt:44 (_add_shared_sources_lib)"

I'm using:
CMAKE 3.16.2
VulkanSDK 1.1.126.0
Windows SDK version 10.0.18362.0
Visual Studio 16 2019

**Comment by mklefrancois** [comment]
Thanks for reporting the issue. Updates were done to CMake in shared_samples and in this directory to allow to run CMake directly from the Tutorial. 
Make sure to update both repositories. 

Regards
