### ISSUE TITLE
matIndex not available in Closest Hit Shader

### ISSUE THREAD

**Issue by michaeleggers** [nvpro-samples/vk_raytracing_tutorial#2]
The `matIndex` buffer does not seem to be available in the .rchit shader.
Following the tutorial at section 12: https://nvpro-samples.github.io/vk_raytracing_tutorial/#simplematerials

**Comment by michaeleggers** [comment]
Noticed one just has to add the following to the raytrace.rchit shader file:

`layout (binding = 4, set = 1, scalar) buffer MatIndex { int i[]; } matIndex[];`

Of course it makes sense but maybe add it to the tutorial as the `set = 1` was important for me,
(cannot just copy paste from the rasterizers fragment shader) otherwise the program would crash as it cannot create the Raytracing-Pipeline properly (in my case).

Also, not that severe but the naming should be consistent across the rasterizer fragment shader and the raytracing hit-shader: In the rasterizer version the array is declared as `matIdx` but in the closest-hit-shader it is `matIndex`, because at section 12 of the tutorial we access the array using:

`int               matIdx = matIndex[objId].i[gl_PrimitiveID];`

**Comment by mklefrancois** [comment]
Thank you, Michael, this will be fixed in the next release.

Note that there is a new version of the tutorial, based on the 'soon to be officially released' VK_KHR_ray_tracing.

https://nvpro-samples.github.io/vk_raytracing_tutorial_KHR/
