### ISSUE TITLE
debugPrintfEXT issue

### ISSUE THREAD

**Issue by UHFT** [nvpro-samples/vk_raytracing_tutorial#3]
I'm using 'debugPrintfEXT' to trace the flow and debug some values.

It works fine for *.vert, *.frag files(passthrough.vert,frag_shader.frag,vert_shader.vert,post.frag) 
 but somehow it does not work on raytrace.* (raytrace.rgen, raytrace.rchit etcs)

It is very frustrating that I cannot use 'debugPrintfEXT' on ray tracing work.

Do you have any ideas or suggestions on how to resolve this issue?

**Comment by pixeljetstream** [comment]
please check the KHR ray tracing extension, maybe more luck there. Closing this issue as the NV extension sample gets archived
